definitions:
  config:
    /hst:platform/hst:hosts/dev-localhost/local:
      jcr:primaryType: hst:virtualhost
      hst:showcontextpath: false
      /dev:
        jcr:primaryType: hst:virtualhost
        /cms:
          jcr:primaryType: hst:virtualhost
          /hst:root:
            jcr:primaryType: hst:mount
            hst:ismapped: false
            hst:namedpipeline: WebApplicationInvokingPipeline
